name: 'MCSManager-Deploy'
description: '将指定的文件通过MCSManager部署到游戏服务器后台'
author: 'ConstasJ'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'copy'
  color: 'white'

# Define your inputs here.
inputs:
  root:
    description: 'MCSManager实例的根URL'
    required: true
  daemon-id:
    description: 'MCSManager节点ID'
    required: true
  server-id:
    description: 'MCSManager服务器实例ID'
    required: true
  api-key:
    description: '用于进行MCSManager实例API操作的API密钥'
    required: true
  source:
    description: '要上传的文件（glob格式）'
    required: true
  target-path:
    description: '对应实例的目标路径'
    required: true

runs:
  using: node20
  main: dist/index.js
